[improve] replace filename checking ci implementation

diff --git a/.github/workflows/doc-build-test.yml b/.github/workflows/doc-build-test.yml
--- a/.github/workflows/doc-build-test.yml
+++ b/.github/workflows/doc-build-test.yml
@@ -34,72 +34,82 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: batista/lint-filenames@v1
-        name: Validating blog filenames
-        with:
-          path: './home/blog'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating docs filenames
-        with:
-          path: './home/docs'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating docs/community filenames
-        with:
-          path: './home/docs/community'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating docs/help filenames
-        with:
-          path: './home/docs/help'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating docs/others filenames
-        with:
-          path: './home/docs/others'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating doc/start filenames
-        with:
-          path: './home/docs/start'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-
-      - uses: batista/lint-filenames@v1
-        name: Validating i18n/blog filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-blog'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating current filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-docs/current'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating current/advanced filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-docs/current/advanced'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating current/community filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating current/help filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating current/others filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-docs/current/others'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
-      - uses: batista/lint-filenames@v1
-        name: Validating current/start filenames
-        with:
-          path: './home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start'
-          pattern: '^[a-z0-9-]+(\.[a-z0-9-]+)+$'
+      - name: Check filename in home/blog
+        run: |
+          TARGET_DIR="./home/blog"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[a-z0-9-]+(\.[a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
+      - name: Check filename in home/docs
+        run: |
+          TARGET_DIR="./home/docs"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[a-z0-9-]+(\.[a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
+      - name: Check filename in /zh-cn/docusaurus-plugin-content-blog
+        run: |
+          TARGET_DIR="./home/i18n/zh-cn/docusaurus-plugin-content-blog"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[a-z0-9-]+(\.[a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
+      - name: Check filename in /home/i18n/zh-cn/docusaurus-plugin-content-docs/current
+        run: |
+          TARGET_DIR="./home/i18n/zh-cn/docusaurus-plugin-content-docs/current"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[a-z0-9-]+(\.[a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi      
 
       - name: NPM INSTALL
         working-directory: home
