[improve] add filename check in home ci

diff --git a/.github/workflows/doc-build-test.yml b/.github/workflows/doc-build-test.yml
--- a/.github/workflows/doc-build-test.yml
+++ b/.github/workflows/doc-build-test.yml
@@ -19,11 +19,11 @@ name: DOC CI
 
 on:
   push:
-    branches: [ master, dev]
+    branches: [ master, dev, filename-check-ci ]
     paths:
       - 'home/**'
   pull_request:
-    branches: [ master, dev]
+    branches: [ master, dev, filename-check-ci ]
     paths:
       - 'home/**'
 
@@ -34,6 +34,82 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+      - name: Check filename in home/blog
+        run: |
+          TARGET_DIR="./home/blog"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[_a-z0-9-]+(\.[_a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
+      - name: Check filename in home/docs
+        run: |
+          TARGET_DIR="./home/docs"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[_a-z0-9-]+(\.[_a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
+      - name: Check filename in /zh-cn/docusaurus-plugin-content-blog
+        run: |
+          TARGET_DIR="./home/i18n/zh-cn/docusaurus-plugin-content-blog"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[_a-z0-9-]+(\.[_a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
+      - name: Check filename in /home/i18n/zh-cn/docusaurus-plugin-content-docs/current
+        run: |
+          TARGET_DIR="./home/i18n/zh-cn/docusaurus-plugin-content-docs/current"
+          invalid_files=()
+          while IFS= read -r -d '' file; do
+            filename=$(basename "$file")
+            if [[ ! "$filename" =~ ^[_a-z0-9-]+(\.[_a-z0-9-]+)*$ ]]; then
+              invalid_files+=("$file")
+            fi
+          done < <(find "$TARGET_DIR" -type f -print0)  
+          if [ ${#invalid_files[@]} -ne 0 ]; then
+            echo "Error: The following files have invalid names:(File name should only contain lowercase letters, numbers, and hyphens.)"
+            for invalid_file in "${invalid_files[@]}"; do
+              echo "$invalid_file"
+            done
+            exit 1
+          else
+            echo "All file names are valid."
+          fi
       - name: NPM INSTALL
         working-directory: home
         run: npm install
